export const testData = {
  commands: [
    {
      id: 13,
      description: "Add jest as dev dependency",
      line: "yarn add --dev jest",
      reference: "https://jestjs.io/docs/26.x/getting-started",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 17,
      description: "Install react hook form",
      line: "yarn add react-hook-form",
      reference: "https://www.react-hook-form.com/get-started",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 18,
      description: "View all dotnet templates",
      line: "dotnet new --list",
      reference:
        "https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-list",
      category: {
        id: 4,
        name: "c#",
      },
    },
    {
      id: 19,
      description: "Install redux toolkit",
      line: "yarn add @reduxjs/toolkit",
      reference: "https://redux-toolkit.js.org/introduction/getting-started",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 20,
      description: "Install Tailwind CSS for Next JS",
      line: "npm install -D tailwindcss@latest postcss@latest autoprefixer@latest",
      reference: "https://tailwindcss.com/docs/guides/nextjs",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 12,
      description: "Install react router v6",
      line: "yarn add history@5 react-router-dom@6",
      reference: "https://reactrouter.com/docs/en/v6",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 21,
      description: "Install supabase",
      line: "npm install @supabase/supabase-js",
      reference:
        "https://supabase.io/docs/guides/with-react#initialize-a-react-app",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 22,
      description: "Create react app with typescript",
      line: "yarn create react-app my-app --template typescript",
      reference: "https://create-react-app.dev/docs/adding-typescript/",
      category: {
        id: 12,
        name: "React",
      },
    },
    {
      id: 23,
      description: "Create react app with chakra ui",
      line: "yarn create react-app my-app --template @chakra-ui/typescript",
      reference: "https://chakra-ui.com/guides/integrations/with-cra",
      category: {
        id: 12,
        name: "React",
      },
    },
    {
      id: 25,
      description: "View globally installed packages",
      line: "npm list -g --depth 0",
      reference: "https://devhints.io/npm",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 26,
      description: "View globally installed packages for yarn",
      line: "yarn global list",
      reference:
        "https://stackoverflow.com/questions/43501514/how-to-display-yarn-globally-installed-packages",
      category: {
        id: 2,
        name: "npm package",
      },
    },
    {
      id: 27,
      description: "Show installed extensions for vscode",
      line: "code --list-extensions",
      reference: "https://code.visualstudio.com/docs/editor/line-line",
      category: {
        id: 1,
        name: "general",
      },
    },
    {
      id: 28,
      description: "VSCode install extension",
      line: "code --install-extension <ext>",
      reference: "https://code.visualstudio.com/docs/editor/line-line",
      category: {
        id: 1,
        name: "general",
      },
    },
    {
      id: 29,
      description: "Delete remote branch",
      line: "git push origin --delete :$branchname",
      reference: "https://devhints.io/git-branch",
      category: {
        id: 14,
        name: "git",
      },
    },
    {
      id: 30,
      description: "Delete local remote-tracking branches",
      line: "git remote prune origin",
      reference: "https://devhints.io/git-branch",
      category: {
        id: 14,
        name: "git",
      },
    },
    {
      id: 31,
      description: "Create site with Gatsby",
      line: "npm init gatsby",
      reference: "https://www.gatsbyjs.com/docs/quick-start/",
      category: {
        id: 12,
        name: "React",
      },
    },
    {
      id: 32,
      description: "Create app with AngularJS",
      line: "ng new my-app",
      reference: "https://angular.io/guide/setup-local",
      category: {
        id: 15,
        name: "Angular",
      },
    },
  ],
  commandCategories: [
    {
      id: 1,
      name: "general",
    },
    {
      id: 2,
      name: "npm package",
    },
    {
      id: 3,
      name: "javascript",
    },
    {
      id: 4,
      name: "c#",
    },
    {
      id: 12,
      name: "React",
    },
    {
      id: 13,
      name: "Vue",
    },
    {
      id: 14,
      name: "git",
    },
    {
      id: 15,
      name: "Angular",
    },
  ],
  links: [
    {
      id: 9,
      url: "https://chakra-ui.com/docs/getting-started",
      title: "Chakra UI",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 10,
      url: "https://tailwindcss.com/docs/installation",
      title: "Tailwind CSS",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 11,
      url: "https://reactrouter.com/docs/en/v6/getting-started/overview",
      title: "React Router",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 13,
      url: "https://beta.reactjs.org/",
      title: "React Docs Beta",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 14,
      url: "https://angular.io/docs",
      title: "Angular",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 15,
      url: "https://redux-toolkit.js.org/introduction/getting-started",
      title: "Redux Toolkit",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 17,
      url: "https://react-icons.github.io/react-icons/",
      title: "React Icons",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 18,
      url: "https://sass-lang.com/guide",
      title: "Sass",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 32,
      url: "https://storybook.js.org/",
      title: "Storybook",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 34,
      url: "https://docs.cypress.io/guides/getting-started/writing-your-first-test",
      title: "Cypress",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 35,
      url: "https://github.com/michalsnik/aos",
      title: "AOS",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 37,
      url: "https://vueformulate.com/guide/installation/#npm",
      title: "Vue formulate",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 43,
      url: "https://formik.org/",
      title: "Formik",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 51,
      url: "https://jestjs.io/docs/api",
      title: "Jest",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 53,
      url: "https://prettier.io/docs/en/install.html",
      title: "Prettier",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 54,
      url: "https://eslint.org/docs/user-guide/getting-started",
      title: "ESLint",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 55,
      url: "https://nextjs.org/docs",
      title: "Next JS",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 58,
      url: "https://docusaurus.io/docs",
      title: "Docusaurus",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 59,
      url: "https://socket.io/docs/v4/",
      title: "Socket.IO",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 61,
      url: "https://axios-http.com/docs/intro",
      title: "Axios",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 62,
      url: "https://react-hook-form.com/get-started",
      title: "React Hook Form",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 79,
      url: "https://playwright.dev/docs/intro",
      title: "Playwright",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 83,
      url: "https://plopjs.com/documentation/#getting-started",
      title: "Plop",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 84,
      url: "https://swiperjs.com/react",
      title: "Swiper JS",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-08T21:14:30",
    },
    {
      id: 87,
      url: "https://www.npmjs.com/package/@azure/msal-react",
      title: "Azure Msal React",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-18T23:38:37",
    },
    {
      id: 88,
      url: "https://www.npmjs.com/package/@azure/msal-browser",
      title: "Azure Msal Browser",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-18T23:39:55",
    },
    {
      id: 89,
      url: "https://react-window.vercel.app/#/examples/list/fixed-size",
      title: "React Window",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-18T23:42:54",
    },
    {
      id: 91,
      url: "https://react-query.tanstack.com/guides/important-defaults",
      title: "React Query",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-23T14:50:00",
    },
    {
      id: 94,
      url: "https://remix.run/docs/en/v1#remix-docs",
      title: "Remix",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-27T13:01:48",
    },
    {
      id: 95,
      url: "https://react-dnd.github.io/react-dnd/docs/overview",
      title: "React DnD",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-03-27T14:13:20",
    },
    {
      id: 99,
      url: "https://react-table.tanstack.com/",
      title: "React Table",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-05T17:28:46",
    },
    {
      id: 105,
      url: "https://testing-library.com/docs/react-testing-library/example-intro",
      title: "React Testing Library",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-05T17:37:26",
    },
    {
      id: 107,
      url: "https://handlebarsjs.com/",
      title: "Handlebars",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-05T17:47:20",
    },
    {
      id: 108,
      url: "https://kit.svelte.dev/docs/introduction",
      title: "SvelteKit",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-06T21:24:52",
    },
    {
      id: 109,
      url: "https://webpack.js.org/concepts/",
      title: "Webpack",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-06T21:25:35",
    },
    {
      id: 110,
      url: "https://parceljs.org/docs/",
      title: "Parcel",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-06T21:26:24",
    },
    {
      id: 115,
      url: "https://jsdoc.app/",
      title: "JSDoc",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-04-06T21:40:27",
    },
    {
      id: 123,
      url: "https://vuejs.org/guide/introduction.html",
      title: "Vue",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-10-28T16:17:04",
    },
    {
      id: 124,
      url: "https://pinia.vuejs.org/introduction.html",
      title: "Pinia",
      previewImageUrl: null,
      faviconImageUrl: null,
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-10-28T16:24:37",
    },
    {
      id: 126,
      url: "https://zod.dev/",
      title: "Zod | Documentation",
      previewImageUrl:
        "https://opengraph.githubassets.com/1cac1150838995e1f7d1643c00eee51a5d884f2054f995c9d3225b07b0eddb39/colinhacks/zod",
      faviconImageUrl: "https://zod.dev/static/favicon-32x32.png",
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-11-01T18:50:26",
    },
    {
      id: 129,
      url: "https://greensock.com/docs/",
      title: "GSAP Docs",
      previewImageUrl:
        "https://greensock.com/uploads/monthly_2020_05/greensock-thumb.png.640b7d423125b0ad11e9f2af1cbf94c9.png",
      faviconImageUrl:
        "https://greensock.com/uploads/monthly_2018_06/favicon.ico.4811a987b377f271db584b422f58e5a7.ico",
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-11-12T00:56:10",
    },
    {
      id: 136,
      url: "https://blaze-slider.dev/docs/intro",
      title: "Blaze Slider",
      previewImageUrl: null,
      faviconImageUrl: "https://blaze-slider.dev/img/favicon.ico",
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-11-12T01:04:46",
    },
    {
      id: 143,
      url: "https://joi.dev",
      title: "joi.dev",
      previewImageUrl: null,
      faviconImageUrl: "https://joi.dev/favicon2.png?v=1.0",
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-11-24T18:01:06",
    },
    {
      id: 144,
      url: "https://inversify.io/",
      title: "InversifyJS",
      previewImageUrl: "http://inversify.io/img/logo_inverse.png",
      faviconImageUrl: "./img/favicon/android-icon-192x192.png",
      starred: false,
      category: {
        id: 2,
        name: "JS Docs",
        displayIndex: 0,
        isGroup: false,
        parentId: 70,
        items: 44,
      },
      dateCreated: "2022-11-24T18:01:52",
    },
  ],
  linkCategories: [
    {
      id: 69,
      name: "C#",
      displayIndex: 0,
      isGroup: true,
      parentId: 0,
      items: 2,
    },
    {
      id: 71,
      name: "Coding Exercises",
      displayIndex: 0,
      isGroup: true,
      parentId: 0,
      items: 1,
    },
    {
      id: 70,
      name: "Frontend",
      displayIndex: 0,
      isGroup: true,
      parentId: 0,
      items: 3,
    },
    {
      id: 13,
      name: "API Docs",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 2,
    },
    {
      id: 11,
      name: "Blog Posts",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 2,
    },
    {
      id: 16,
      name: "C# Docs",
      displayIndex: 0,
      isGroup: false,
      parentId: 69,
      items: 5,
    },
    {
      id: 64,
      name: "C# Tutorials",
      displayIndex: 0,
      isGroup: false,
      parentId: 69,
      items: 2,
    },
    {
      id: 10,
      name: "Cloud services",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 14,
    },
    {
      id: 12,
      name: "Coding problems",
      displayIndex: 0,
      isGroup: false,
      parentId: 71,
      items: 5,
    },
    {
      id: 8,
      name: "Companies",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 2,
    },
    {
      id: 5,
      name: "CSS",
      displayIndex: 0,
      isGroup: false,
      parentId: 70,
      items: 14,
    },
    {
      id: 76,
      name: "Dev News",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 1,
    },
    {
      id: 72,
      name: "DevOps",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 1,
    },
    {
      id: 74,
      name: "Example Repos",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 1,
    },
    {
      id: 7,
      name: "HTML",
      displayIndex: 0,
      isGroup: false,
      parentId: 70,
      items: 3,
    },
    {
      id: 2,
      name: "JS Docs",
      displayIndex: 0,
      isGroup: false,
      parentId: 70,
      items: 44,
    },
    {
      id: 6,
      name: "Learning Resources",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 13,
    },
    {
      id: 77,
      name: "MDN Docs",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 0,
    },
    {
      id: 4,
      name: "Other",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 0,
    },
    {
      id: 1,
      name: "Portfolios",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 24,
    },
    {
      id: 14,
      name: "Project Management",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 1,
    },
    {
      id: 9,
      name: "Projects",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 5,
    },
    {
      id: 15,
      name: "Solutions to problems",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 1,
    },
    {
      id: 75,
      name: "Typing Sites",
      displayIndex: 0,
      isGroup: false,
      parentId: 0,
      items: 3,
    },
  ],
};
